create table CUSTOMERS
(
    ID NUMBER(4) PRIMARY KEY,
    "NAME" VARCHAR2(30) NOT NULL,
);

create table EMPLOEES
(
    ID NUMBER(4) PRIMARY KEY,
    "NAME" VARCHAR2(30) NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL
);

create table CHECKS
(
    ID NUMBER(4) PRIMARY KEY,
    FOREIGN KEY (ID_EMPLOEE) REFERENCES EMPLOEE(ID),
    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER(ID),
    "DATE" DATE,
    AMOUNT NUMBER(10),
);

create table PRODUCTS
(
    ID NUMBER(4) PRIMARY KEY,
    "NAME" VARCHAR2(10) NOT NULL,
    PRICE NUMBER(4) NOT NULL,
);

create table PRODUCT_CHECK
(
    "NUMBER" NUMBER(4) PRIMARY KEY,
    FOREIGN KEY (ID_CHECK) REFERENCES CHECK(ID),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID),
);

-- edit from githab 2
