create table CUSTOMERS
(
    ID NUMBER(4) PRIMARY KEY,
    "NAME" VARCHAR2(30) NOT NULL
);

create table EMPLOEES
(
    ID NUMBER(4) PRIMARY KEY,
    "NAME" VARCHAR2(30) NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL
);

create table CHECKS
(
    ID NUMBER(4) PRIMARY KEY,

    "DATE" DATE,
    AMOUNT NUMBER(10),
    ID_EMPLOEE NUMBER(10),
    ID_CUSTOMER NUMBER(10),
    FOREIGN KEY (ID_EMPLOEE) REFERENCES EMPLOEES(ID),
    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
);

create table PRODUCTS
(
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL,
    PRICE NUMBER(4) NOT NULL
);

create table PRODUCT_CHECK
(
    "NUMBER" NUMBER(4) PRIMARY KEY,
    ID_CHECK NUMBER(4),
    ID_PRODUCT NUMBER(4),
    FOREIGN KEY (ID_CHECK) REFERENCES CHECKS(ID),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID)
);